spring.application.name=com.netflix.clone

spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/pulsescreen_video
spring.datasource.username = root
spring.datasource.password = 1234
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.formate-sql = true

spring.servlet.multipart.enabled = true
spring.servlet.multipart.max-file-size = 2GB
spring.servlet.multipart.max-request-size = 2GB

server.tomcat.max-swallow-size =-1
server.tomcat.max-http-form-post-size=-1

file.upload.video-dir =uploads/video
file.upload.image-dir =uploads/image

spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = prathameshwalekar9@gmail.com
spring.mail.password=fvlp hbvw uhsf uapd
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true
spring.mail.properties.mail.smtp.starttls.required = true
spring.mail.properties.mail.smtp.connection-timeout = 5000
spring.mail.properties.mail.smtp.timeout = 5000
spring.mail.properties.mail.smtp.writetimeout = 5000
app.frontend.url = http://localhost:4200